### ISSUE TITLE
请问博客中简书和 Medium 的 db.js 是怎么生成的呢？

### ISSUE THREAD

**Issue by ximuli** [Haixiang6123/blog#4]
你好，你的博客风格很美，我可以参考着用来做一个自己的吗？
如题，看到你的博客中有自己的博文列表，所以比较好奇是怎么实现的。
我查看源码后发现简书和 Medium 组件的所在的文件夹中都有用来存放文章信息的 db.js 文件，所以想请教下这两个文件是如何生成的呢？
望赐教，感谢。

**Comment by haixiangyan** [comment]
db.js 文件里存的都是文章的标题和url，点击后会跳转到对应的简书和 Medium文章。这个可以使用爬虫来生成。
